# Generated by Django 4.0.5 on 2022-06-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.PositiveIntegerField(unique=True, verbose_name='etiqueta')),
                ('fechado', models.BooleanField(default=False, verbose_name='fechado')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=512, verbose_name='razão social')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'tipo de lançamento',
                'verbose_name_plural': 'tipo de lançamento',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='ultima modificação')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquivo.arquivo', verbose_name='arquivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquivo.cliente', verbose_name='cliente')),
                ('tipo_de_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquivo.tipodelancamento', verbose_name='tipo de lançamento')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
            },
        ),
    ]
