# Generated by Django 4.0.5 on 2022-06-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='ultima modificação')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquivo.arquivo', verbose_name='arquivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquivo.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.RenameModel(
            old_name='TipoDeLancamento',
            new_name='TipoDeDocumento',
        ),
        migrations.DeleteModel(
            name='Lancamento',
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_de_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquivo.tipodedocumento', verbose_name='tipo de documento'),
        ),
    ]
