# Generated by Django 4.0.5 on 2023-01-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arquivo', '0004_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='modificado_em',
        ),
        migrations.AddField(
            model_name='documento',
            name='cheia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_arquivo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_finalizacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_saida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='numero_caixa',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='documento',
            name='observacao',
            field=models.CharField(max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arquivo.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_de_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arquivo.tipodedocumento', verbose_name='tipo de documento'),
        ),
    ]
