# Generated by Django 4.0.5 on 2023-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0005_remove_documento_conteudo_remove_documento_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='atividade',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sigla_estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone1',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_contato',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(max_length=512, null=True, verbose_name='razão social'),
        ),
    ]
