# Generated by Django 4.0.5 on 2023-01-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0006_cliente_atividade_cliente_bairro_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='complemento',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
