# Generated by Django 5.1.1 on 2025-03-18 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arquivo", "0007_historico_complemento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"ordering": ["nome", "razao_social"]},
        ),
        migrations.AlterModelOptions(
            name="documento",
            options={
                "ordering": ["-data_arquivo"],
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
            },
        ),
        migrations.AlterField(
            model_name="cliente",
            name="atividade",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="data_cadastro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="inscricao_estadual",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="razao_social",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="razão social"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="sigla_estado",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone1",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone_contato",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo_pessoa",
            field=models.CharField(
                choices=[("F", "Pessoa Física"), ("J", "Pessoa Jurídica")],
                default="F",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="data_arquivo",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="data_finalizacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="data_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="data_saida",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="observacao",
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name="historico",
            name="complemento",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name="historico",
            name="data",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="historico",
            name="nome_user",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
