# Generated by Django 5.2.6 on 2025-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arquivo", "0008_alter_cliente_options_alter_documento_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="numero_caixa",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
