# Generated by Django 5.1.7 on 2025-03-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0008_alter_cliente_options_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero_caixa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
