# Generated by Django 5.1.7 on 2025-03-26 00:31

from django.db import migrations

def forward(apps, schema_editor):
    Documento = apps.get_model("arquivo", "Documento")
    db_alias = schema_editor.connection.alias
    Documento.objects.using(db_alias).filter(numero_caixa=-1.0).update(numero_caixa=None)

def reverse(apps, schema_editor):
    Documento = apps.get_model("arquivo", "Documento")
    db_alias = schema_editor.connection.alias
    Documento.objects.using(db_alias).filter(numero_caixa=None).update(numero_caixa=-1.0)


class Migration(migrations.Migration):

    dependencies = [
        ("arquivo", "0009_alter_documento_numero_caixa"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
