# Generated by Django 5.1.7 on 2025-03-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arquivo", "0010_auto_20250325_2131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="numero_caixa",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
