[tool.poetry]
name = "arquivo"
version = "0.1.0"
description = ""
authors = ["Carlos Augusto Monoo Pereira Barbosa <augustomonoo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.5"

[tool.poetry.dev-dependencies]
django-extensions = "^3.1.5"
django-livereload-server = "^0.4"
django-debug-toolbar = "^3.4.0"
black = "^22.3.0"
Werkzeug = "^2.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
